/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory.$id'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory.new'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedSalesIdRouteImport } from './routes/_authenticated/sales.$id'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales.new'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesIdRoute = AuthenticatedSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/sales/$id': typeof AuthenticatedSalesIdRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/sales/$id': typeof AuthenticatedSalesIdRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/sales/$id': typeof AuthenticatedSalesIdRoute
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reports'
    | '/team'
    | '/customers/$id'
    | '/inventory/$id'
    | '/inventory/new'
    | '/sales/$id'
    | '/sales/new'
    | '/customers/'
    | '/inventory/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reports'
    | '/team'
    | '/'
    | '/customers/$id'
    | '/inventory/$id'
    | '/inventory/new'
    | '/sales/$id'
    | '/sales/new'
    | '/customers'
    | '/inventory'
    | '/sales'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/reports'
    | '/_authenticated/team'
    | '/_authenticated/'
    | '/_authenticated/customers/$id'
    | '/_authenticated/inventory/$id'
    | '/_authenticated/inventory/new'
    | '/_authenticated/sales/$id'
    | '/_authenticated/sales/new'
    | '/_authenticated/customers/'
    | '/_authenticated/inventory/'
    | '/_authenticated/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/$id': {
      id: '/_authenticated/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/$id': {
      id: '/_authenticated/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AuthenticatedSalesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedSalesIdRoute: typeof AuthenticatedSalesIdRoute
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRoute,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedSalesIdRoute: AuthenticatedSalesIdRoute,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
